### PR TITLE
lang : Japanese translation. 

### PR DESCRIPTION
**Pull request by haniwa55**
I made Japanese translation.
I will make a pull request.
There is encrypt & encode methods of ArcCPZ.cs used in my PB3 replacement program.
I copied original source decrypt & decode methods and made encrypt & encode methods.
If you can reuse it I will make a pull request.
if it unless necessary I will not make a pull request.

### CODE REVIEW

**Comment by haniwa55** [comment]
ArcCPZ.cs encrypt & encode methods
https://github.com/haniwa55/GARbro/commit/f4931f0b0fc75eddb6520909217dc7b6eaedb244

**Comment by haniwa55** [comment]
I'm sorry.
I made a mistake again.
I committed encrypt & encode methods after pull request.
If methods are unnecessary, I will start over again from the beginning.

**Comment by haniwa55** [comment]
Thank you very much for supporting Japanese with GARbro.
I saw some source programs of GARbro.
Beyond my imagination a lot of amazing decrypt methods were coded.
What tools can I use to analyze exe and I can do such amazing coding?
If your analysis technology is top secret you do not have to answer my question.
Please let me know if you can publish your analysis technology or analysis tools name.

**Comment by morkt** [comment]
it's no secret, the most useful tool is IDA with Decompiler add-on. analysis is too broad topic to be answered here. in short, you need to locate some specific function to reverse engineer it. what function and how to do it largely depends on a task. usually it's done by analyzing references to file signatures or system function calls. of course, you have to be familiar with x86 assembler and win32 API. if you have further questions better open new issue, i'll try to answer what i can there.

**Comment by haniwa55** [comment]
I understand.
I will study IDA with Decompiler add-on from now.
https://github.com/onethawt/idaplugins-list
Would you please tell me the name of IDA with Decompiler add-on if you like?
I will open a new issa for the next question.
Thank you very much for your answer despite being so busy.

**Pull request merged**
